module _notificacao {


  interface NotificacaoInterface {

    string getNotificacoes(in long idUsuario);
	boolean criarNotificacao(in long idUsuario, in long tipoNotificacao, in long idDesejoOferta);

  };


};
