package _notificacao;


/**
* _notificacao/NotificacaoInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./br/org/furb/corba/notificacao/NotificacaoCORBA.idl
* Sábado, 29 de Novembro de 2014 18h42min47s BRST
*/

public abstract class NotificacaoInterfacePOA extends org.omg.PortableServer.Servant
 implements _notificacao.NotificacaoInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getNotificacoes", new java.lang.Integer (0));
    _methods.put ("criarNotificacao", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // _notificacao/NotificacaoInterface/getNotificacoes
       {
         int idUsuario = in.read_long ();
         String $result = null;
         $result = this.getNotificacoes (idUsuario);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // _notificacao/NotificacaoInterface/criarNotificacao
       {
         int idUsuario = in.read_long ();
         int tipoNotificacao = in.read_long ();
         int idDesejoOferta = in.read_long ();
         boolean $result = false;
         $result = this.criarNotificacao (idUsuario, tipoNotificacao, idDesejoOferta);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:notificacao/NotificacaoInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public NotificacaoInterface _this() 
  {
    return NotificacaoInterfaceHelper.narrow(
    super._this_object());
  }

  public NotificacaoInterface _this(org.omg.CORBA.ORB orb) 
  {
    return NotificacaoInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class NotificacaoInterfacePOA
