package _notificacao;


/**
* _notificacao/NotificacaoInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./br/org/furb/corba/notificacao/NotificacaoCORBA.idl
* Sábado, 29 de Novembro de 2014 16h44min39s BRST
*/

public interface NotificacaoInterfaceOperations 
{
  String getNotificacoes (int idUsuario);
  boolean criarNotificacao (int idUsuario, int tipoNotificacao, int idDesejoOferta);
} // interface NotificacaoInterfaceOperations
