package _notificacao;


/**
* _notificacao/NotificacaoInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./br/org/furb/corba/notificacao/NotificacaoCORBA.idl
* Sábado, 29 de Novembro de 2014 18h42min47s BRST
*/

public interface NotificacaoInterface extends NotificacaoInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NotificacaoInterface
