package _notificacao;


/**
* _notificacao/NotificacaoInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./br/org/furb/corba/notificacao/NotificacaoCORBA.idl
* Sábado, 29 de Novembro de 2014 14h09min53s BRST
*/

public interface NotificacaoInterfaceOperations 
{
  String getNotificoes (int idUsuario);
  boolean criarNotificacao (int idUsuario, int tipoNotificacao);
} // interface NotificacaoInterfaceOperations
