
package br.org.furb.ws.usuario.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsuarioWS", targetNamespace = "http://usuario.ws.furb.org.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsuarioWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns br.org.furb.ws.usuario.cliente.Usuario
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "autenticar", targetNamespace = "http://usuario.ws.furb.org.br/", className = "br.org.furb.ws.usuario.cliente.Autenticar")
    @ResponseWrapper(localName = "autenticarResponse", targetNamespace = "http://usuario.ws.furb.org.br/", className = "br.org.furb.ws.usuario.cliente.AutenticarResponse")
    @Action(input = "http://usuario.ws.furb.org.br/UsuarioWS/autenticarRequest", output = "http://usuario.ws.furb.org.br/UsuarioWS/autenticarResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://usuario.ws.furb.org.br/UsuarioWS/autenticar/Fault/Exception")
    })
    public Usuario autenticar(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscar", targetNamespace = "http://usuario.ws.furb.org.br/", className = "br.org.furb.ws.usuario.cliente.Buscar")
    @ResponseWrapper(localName = "buscarResponse", targetNamespace = "http://usuario.ws.furb.org.br/", className = "br.org.furb.ws.usuario.cliente.BuscarResponse")
    @Action(input = "http://usuario.ws.furb.org.br/UsuarioWS/buscarRequest", output = "http://usuario.ws.furb.org.br/UsuarioWS/buscarResponse")
    public String buscar(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.org.furb.ws.usuario.cliente.Usuario
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarUser", targetNamespace = "http://usuario.ws.furb.org.br/", className = "br.org.furb.ws.usuario.cliente.BuscarUser")
    @ResponseWrapper(localName = "buscarUserResponse", targetNamespace = "http://usuario.ws.furb.org.br/", className = "br.org.furb.ws.usuario.cliente.BuscarUserResponse")
    @Action(input = "http://usuario.ws.furb.org.br/UsuarioWS/buscarUserRequest", output = "http://usuario.ws.furb.org.br/UsuarioWS/buscarUserResponse")
    public Usuario buscarUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "criarUsuario", targetNamespace = "http://usuario.ws.furb.org.br/", className = "br.org.furb.ws.usuario.cliente.CriarUsuario")
    @ResponseWrapper(localName = "criarUsuarioResponse", targetNamespace = "http://usuario.ws.furb.org.br/", className = "br.org.furb.ws.usuario.cliente.CriarUsuarioResponse")
    @Action(input = "http://usuario.ws.furb.org.br/UsuarioWS/criarUsuarioRequest", output = "http://usuario.ws.furb.org.br/UsuarioWS/criarUsuarioResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://usuario.ws.furb.org.br/UsuarioWS/criarUsuario/Fault/Exception")
    })
    public boolean criarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        Usuario arg0)
        throws Exception_Exception
    ;

}
