package _anuncio;

/**
* _anuncio/AnuncioInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./br/org/furb/corba/anuncio/AnuncioCORBA.idl
* Sábado, 29 de Novembro de 2014 14h09min52s BRST
*/

public final class AnuncioInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public _anuncio.AnuncioInterface value = null;

  public AnuncioInterfaceHolder ()
  {
  }

  public AnuncioInterfaceHolder (_anuncio.AnuncioInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = _anuncio.AnuncioInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    _anuncio.AnuncioInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return _anuncio.AnuncioInterfaceHelper.type ();
  }

}
