package BoasVindas;


/**
* BoasVindas/Msg_Boas_VindasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/org/furb/corba/notificacao/NotificacaoBoasVindas.idl
* Quarta-feira, 26 de Novembro de 2014 21h05min33s BRST
*/

public interface Msg_Boas_VindasOperations 
{
  String boas_vindas ();
} // interface Msg_Boas_VindasOperations
