package _anuncio;


/**
* _anuncio/AnuncioInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./br/org/furb/corba/anuncio/AnuncioCORBA.idl
* Quinta-feira, 27 de Novembro de 2014 19h21min00s BRST
*/

public interface AnuncioInterfaceOperations 
{
  String getAnuncios (int idUsuario);
} // interface AnuncioInterfaceOperations
