package _anuncio;


/**
* _anuncio/AnuncioInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./br/org/furb/corba/anuncio/AnuncioCORBA.idl
* Sábado, 29 de Novembro de 2014 18h42min46s BRST
*/

public interface AnuncioInterface extends AnuncioInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AnuncioInterface
